# Generated by Django 5.1.6 on 2025-03-05 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='news_thums/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('SPOTRS', 'SPORTS'), ('BUSINESS', 'BUSINESS'), ('TECHNOLOGY', 'TECHNOLOGY'), ('POLITICS', 'POLITICS'), ('STOCK', 'STOCK')], max_length=20)),
            ],
        ),
    ]
