# Generated by Django 5.1.6 on 2025-03-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsvarity',
            name='author',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='newsvarity',
            name='description',
            field=models.TextField(default='default desc'),
        ),
        migrations.AddField(
            model_name='newsvarity',
            name='title',
            field=models.CharField(default='default title', max_length=25),
        ),
    ]
